# Site settings
site: Abhijith
title: Abhijith
keywords: abhijith, blog
description: >-
  Abhijith's personal blog.
lang: en-US
timezone:  Asia/Kolkata
#repo: https://github.com/onepase/Ephesus # site repo [optional]
#google_verify:      XXX # Put your Google Verification here
#google_analytics:   UA-XXXXXXXX-00 # Put your Google Analytics code
#discus-identifier:  XXX

# Author settings
author:
  name: Abhijith
  bio: Photographer <br> Doctor<br> KL, IN
  picture: assets/images/profile.jpg 
  #github: onepase # github username
  twitter: abhijithgopans # twitter username
  #facebook: onepase # facebook username
  instagram: abhijithgopans # instagram username
  #youtube: https://www.youtube.com/channel/UCMmAto-wxBootXN91AzBiDg # youtube username
  #linkedin: hakantorun # linkedin username
  #email: your-email@email.com # email adress


# URL settings
url: http://abhijithgopan.github.io # Domain Name of host. [username].github.io for github pages
permalink: pretty

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge


exclude:
  - .jekyll-cache
  - .obsidian
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - CONTRIBUTING.md

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-relative-links
paginate: 20
paginate_path: "/page/:num"

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

relative_links:
  enabled:     true
  collections: false